import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer"; // adjust the path if different
import Navbar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "TEDxBITJaipur",
  description: "Generated by create next app",
  icons: {
    icon: "/vercel.svg", // Changed to vercel.svg
    shortcut: "/vercel.svg",
    apple: "/vercel.svg", // optional, for Apple devices
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <Navbar />
        {children}
        <Footer /> {/* 🔥 Footer visible on all pages */}
      </body>
    </html>
  );
}
